name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
            automated
          git-author-name: "${{ secrets.COMMITTER_NAME }}"
          git-author-email: "${{ secrets.COMMITTER_EMAIL }}"
          git-committer-name: "${{ secrets.COMMITTER_NAME }}"
          git-committer-email: "${{ secrets.COMMITTER_EMAIL }}"
      - name: Auto-merge PR
        run: gh pr merge --auto --rebase "https://github.com/${{ github.repository_owner }}/${{ github.repository }}/pull/${{ steps.update.outputs.pull-request-number }}"
      - name: Print PR URL
        run: echo Pull request created at https://github.com/${{ github.repository_owner }}/${{ github.repository }}/pull/${{ steps.update.outputs.pull-request-number }}
